services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: book_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stoped
  
  mail-div:
    container_name: mail-dev-dsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local
